#!/bin/bash
#######################################################################
#
# Fichier :        goTidy
#
# Description: Tidy est mieux utilisé dans une boucle mais les Makefiles ne
# font des bonnes boucles bash. Ce fichier supprime ce problème.
#
# Auteur :      James Robertson
#
########################################################################

for file in `find "$1" -name "*.html"`; do
        tidy -config tidy.conf $file
done

exit 0
