#!/bin/bash
# affiche les modifications de la copie locale par rapport
# à la version SVN correspondante
# Denis Mugnier
# myou72@orange.fr
# 13/05/12

VERSION=$(svn info | grep "R.vision *:" | sed -e "s/^.*: \([0-9][0-9]*\)/\1/")
echo "Votre copie locale correspond à la version $VERSION du SVN"
svn -r$VERSION diff

exit 0
