[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name "arquivo general.ent do lfs"

[options] --package-version 1.0

[options] --keep 0

[options] --width 72

[options] --wrap-po 72

[po4a_langs] pt_BR

[po4a_paths] text/po/$master.pot pt_BR:text/po/$master.$lang.po

[type: text] text/upstream/general.ent pt_BR:text/translated/general.$lang.ent
