#!/bin/sh

# Copie les fichiers modèle et remplace template avec le nom du paquetage donné,
# simplifiant grandement le processus d'ajout d'un nouveau paquetage.

if [ -z "$1" ]
then
  echo "Crée des fichiers modèle pour un paquetage et remplit avec le nom du paquetage."
  echo "Usage: $0 <nom-paquetage> <nom-fichier-paquetage>"
  echo
  echo "Notez que si vous voulez créer le paquetage Glib, vous devriez appeler"
  echo "le script de cette façon: '$0 Glib glib' de façon à ce que les noms de fichiers"
  echo "soient en minuscule. Si vous spécifiez seulement la première option, il est utilisé"
  echo "pour les deux."
  echo "Notez aussi que *tous* les noms de fichiers dans BLFS devraient être uniquement en minuscule."
  exit 1
fi

WRITTENNAME=$1

if [ -z "$2" ]
then
 FILENAME=$WRITTENNAME
else
 FILENAME=$2
fi

pushd `dirname $0`
TEMPLDIR=`pwd`
popd
 
for i in $TEMPLDIR/template*
do
  NEWFILE=`echo $i | sed s@$TEMPLDIR/template@$FILENAME@`
  echo $NEWFILE
  sed s/template/$WRITTENNAME/g $i > $NEWFILE
done
